# Generated by Django 5.0.3 on 2024-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medical_licence_number', models.IntegerField()),
                ('place_of_practice', models.TextField()),
            ],
        ),
    ]
