# Generated by Django 5.0.3 on 2024-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medics',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medics',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
    ]
