# Generated by Django 5.0.3 on 2024-03-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapi', '0002_medics_age_medics_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medics',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
